Class {
	#name : #NullBox,
	#superclass : #Object,
	#instVars : [
		'state'
	],
	#category : #'IngSoft2-Model'
}

{ #category : #'Instance creation' }
NullBox class >> initializeNew [

	^ self new initializeNew
]

{ #category : #Effect }
NullBox >> effect: aDuplaGalacticaGame [

	
]

{ #category : #Initialization }
NullBox >> initializeNew [
]

{ #category : #Effect }
NullBox >> reversePolarity [

	
]
